# Generated by Django 2.2.7 on 2019-11-24 09:07

import autoslug.fields
from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Add the name of of the anime and the Episode no. (Eg: One Punch Man S1E1)', max_length=200, null=True, verbose_name='Descripton')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='description')),
                ('link', models.CharField(help_text='Enter the link of the episode', max_length=5000, verbose_name='Link')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Episodes',
            },
        ),
        migrations.CreateModel(
            name='NewAnime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Enter the official Name of the Anime', max_length=80, null=True, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('thumbnail', optimized_image.fields.OptimizedImageField(help_text='Upload the Official Anime Poster', null=True, upload_to='uploads', verbose_name='Thumbanail')),
                ('description', models.TextField(help_text='A breif summary about the Anime', max_length=200, null=True, verbose_name='Descripton')),
                ('genre', models.CharField(help_text='Add Genres or tags seperated by a commar (Eg: Shounen, Horror)', max_length=80, null=True, verbose_name='Genre/Categories')),
                ('rating', models.DecimalField(decimal_places=1, help_text='Add ratings with only two digits (Eg: 4.5 or 5.0 ', max_digits=2, null=True, verbose_name='Ratings')),
                ('date', models.DateTimeField(auto_now=True)),
                ('episodes', models.ManyToManyField(to='dashboard.Episodes')),
                ('similar_shows', models.ManyToManyField(blank=True, help_text='Add similar shows like this one to be shown as recommended', related_name='_newanime_similar_shows_+', to='dashboard.NewAnime', verbose_name='Similar')),
            ],
            options={
                'verbose_name_plural': 'Animes',
            },
        ),
    ]
