# Generated by Django 2.2.7 on 2019-11-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191124_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newanime',
            name='thumbnail',
            field=models.ImageField(help_text='Upload the Official Anime Poster', null=True, upload_to='media/', verbose_name='Thumbanail'),
        ),
    ]
