# Generated by Django 2.2.7 on 2019-11-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191124_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodes',
            old_name='slug',
            new_name='ep_slug',
        ),
    ]
