# Generated by Django 2.2.7 on 2019-11-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191124_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newanime',
            name='description',
            field=models.TextField(help_text='A breif summary about the Anime', max_length=1500, null=True, verbose_name='Descripton'),
        ),
    ]
