# Generated by Django 2.2.7 on 2019-11-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_episodes_episode_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='newanime',
            name='thumbnail_url',
            field=models.CharField(help_text='Provide the link for the official Poster (Google it!)', max_length=80, null=True, verbose_name='Thumbnail url'),
        ),
    ]
