# Generated by Django 2.2.7 on 2019-11-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_newanime_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newanime',
            name='thumbnail_url',
            field=models.CharField(help_text='Provide the link for the official Poster (Google it!)', max_length=2000, null=True, verbose_name='Thumbnail url'),
        ),
    ]
