# Generated by Django 2.2.7 on 2019-11-26 08:47

from django.db import migrations
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20191126_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newanime',
            name='thumbnail',
            field=optimized_image.fields.OptimizedImageField(blank=True, help_text='Upload the Official Anime Poster', null=True, upload_to='media/', verbose_name='Thumbanail'),
        ),
    ]
