# Generated by Django 2.2.7 on 2019-11-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20191126_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='newanime',
            name='language',
            field=models.IntegerField(choices=[('Sub', 'SUB'), ('Dub', 'DUB')], default=None, null=True, verbose_name='Language'),
        ),
    ]
