# Generated by Django 2.2.7 on 2019-11-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_newanime_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newanime',
            name='language',
            field=models.CharField(choices=[('-', 'None'), ('Sub', 'SUB'), ('Dub', 'DUB')], default=None, max_length=8, null=True, verbose_name='Language'),
        ),
    ]
