# Generated by Django 2.2.7 on 2019-12-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20191203_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newanime',
            name='rating',
        ),
    ]
