# Generated by Django 2.2.7 on 2019-12-13 22:42

import autoslug.fields
from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_newanime_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Enter the official Name of the Anime', max_length=80, null=True, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('thumbnail', optimized_image.fields.OptimizedImageField(blank=True, help_text='Upload the Official Anime Poster', null=True, upload_to='media/', verbose_name='Thumbanail')),
                ('thumbnail_url', models.CharField(help_text='Provide the link for the official Poster (Google it!)', max_length=2000, null=True, verbose_name='Thumbnail url')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Image Banner',
                'ordering': ['-date'],
            },
        ),
    ]
