# Generated by Django 2.2.7 on 2019-12-14 02:32

import autoslug.fields
from django.db import migrations, models
import optimized_image.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(help_text='Enter the official Name of the Anime', max_length=80, null=True, verbose_name='Title')),
                ('message', optimized_image.fields.OptimizedImageField(blank=True, help_text='Upload the Official Anime Poster', null=True, upload_to='media/', verbose_name='Thumbanail')),
                ('email', models.CharField(help_text='Provide the link for the official Poster (Google it!)', max_length=2000, null=True, verbose_name='Thumbnail url')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Enter the official Name of the Anime', max_length=80, null=True, verbose_name='Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('thumbnail', optimized_image.fields.OptimizedImageField(blank=True, help_text='Upload the Official Anime Poster', null=True, upload_to='media/', verbose_name='Thumbanail')),
                ('thumbnail_url', models.CharField(help_text='Provide the link for the official Poster (Google it!)', max_length=2000, null=True, verbose_name='Thumbnail url')),
                ('description', models.TextField(help_text='A breif summary about the Anime', max_length=1500, null=True, verbose_name='Descripton')),
                ('language', models.CharField(choices=[('Sub', 'SUB'), ('Dub', 'DUB')], default='SUB', max_length=8, null=True, verbose_name='Language')),
                ('genre', models.CharField(help_text='Add Genres or tags seperated by a commar (Eg: Shounen, Horror)', max_length=80, null=True, verbose_name='Genre/Categories')),
                ('link', models.CharField(help_text='Enter the link of the movie', max_length=5000, verbose_name='Link')),
                ('date', models.DateTimeField(auto_now=True)),
                ('similar_shows', models.ManyToManyField(blank=True, help_text='Add similar shows like this one to be shown as recommended', related_name='_movies_similar_shows_+', to='dashboard.Movies', verbose_name='Similar')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['-date'],
            },
        ),
    ]
