# Generated by Django 2.2.7 on 2019-12-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_contacts_movies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='date',
        ),
    ]
