# Generated by Django 2.2.7 on 2019-12-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20191214_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='message',
            field=models.TextField(max_length=2000, null=True, verbose_name='Message'),
        ),
    ]
