# Generated by Django 2.2.7 on 2019-12-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_contacts_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(max_length=2000, null=True, verbose_name='Sender Email'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='full_name',
            field=models.TextField(max_length=80, null=True, verbose_name='Name'),
        ),
    ]
